"""Single source of truth for everything identity/version-shaped in the build.

The Windows installer pipeline has four consumers that must agree with each
other: the Python package (``jautomatic.__version__``), the frozen executable's
version resource, the MSI's ``ProductVersion`` (and therefore the ARP entry) and
the release asset names. They are all derived here, from one place.

Rules that matter (and are enforced by ``tests/test_packaging.py``):

* ``__version__`` is the only version you edit. Everything else is derived.
* MSI ``ProductVersion`` is ``major.minor.build`` only - Windows Installer
  silently ignores a fourth field when comparing versions, so a 4-part version
  would make two different releases look identical to the upgrade engine.
* The executable's file version gets the fourth field padded with 0.
* The ``UpgradeCode`` is a *fixed* GUID: it is the identity that lets Windows
  recognise "same product, newer version". Changing it silently installs
  side-by-side instead of upgrading, so it is derived deterministically from
  the repository URL and must never be regenerated casually.

Pure standard library: this module is imported by the PyInstaller spec, the
PowerShell build script, CI and the test suite - it must work before any
dependency is installed.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from pathlib import Path

PACKAGING_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGING_DIR.parent

PRODUCT_NAME = "JAUTOMATIC JOB SEARCH"
PRODUCT_SLUG = "jautomatic-job-search"
PUBLISHER = "JAUTOMATIC"
EXE_BASENAME = "JAUTOMATIC"
EXE_NAME = f"{EXE_BASENAME}.exe"
INSTALL_FOLDER = PRODUCT_NAME
REGISTRY_KEY = rf"Software\{PUBLISHER}\{PRODUCT_SLUG}"
PROJECT_URL = "https://github.com/eugenshila/JAUTOMATIC-JOB-SEARCH"

#: Fixed forever. Derived once (uuid5 over the repo URL) so a fresh clone and a
#: five-year-old checkout always agree. See the module docstring.
UPGRADE_CODE = "9af86a17-eb3b-5133-abe2-1d58466e83a6"

#: Namespace used if a stable per-item GUID is ever needed (shortcuts, etc.).
COMPONENT_NAMESPACE = uuid.UUID("28a52d65-a1c6-595e-8733-e1acc612d94e")

# WiX/PyInstaller pinning - keep in sync with packaging/.config/dotnet-tools.json
WIX_VERSION = "5.0.2"
WIX_EXTENSIONS = {
    "WixToolset.UI.wixext": WIX_VERSION,
    "WixToolset.Util.wixext": WIX_VERSION,
}

# Minimum Windows for the MSI launch condition, as an OS *build* number: MSI's
# VersionNT property is unreliable on Windows 8.1+, but WindowsBuildNumber is
# not. 10240 is the first Windows 10 release.
MIN_WINDOWS_BUILD = 10240


def read_version(source: Path | None = None) -> str:
    """Parse ``__version__`` out of ``jautomatic/__init__.py`` without importing it.

    Importing the package would require its dependencies; the build script runs
    before they exist.
    """
    text = (source or REPO_ROOT / "jautomatic" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', text, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"could not find __version__ in {source or 'jautomatic/__init__.py'}")
    return match.group(1)


def version_tuple(version: str) -> tuple[int, ...]:
    parts = re.findall(r"\d+", version)
    if not parts:
        raise ValueError(f"version has no numeric part: {version!r}")
    return tuple(int(p) for p in parts[:4])


def msi_version(version: str) -> str:
    """MSI ProductVersion: exactly three numeric fields (the upgrade-relevant part)."""
    major, minor, patch = (list(version_tuple(version)) + [0, 0, 0])[:3]
    return f"{major}.{minor}.{patch}"


def file_version(version: str) -> str:
    """Win32 file version: four fields, fourth padded."""
    major, minor, patch, build = (list(version_tuple(version)) + [0, 0, 0, 0])[:4]
    return f"{major}.{minor}.{patch}.{build}"


def release_name(version: str, arch: str = "x64") -> str:
    """Asset base name, e.g. ``JAUTOMATIC-JOB-SEARCH-1.2.0-x64``."""
    return f"{PRODUCT_NAME.replace(' ', '-')}-{msi_version(version)}-{arch}"


VERSION_INFO_TEMPLATE = """# Auto-generated by packaging/build_info.py - do not edit by hand.
# PyInstaller version resource (Windows only): gives JAUTOMATIC.exe real file
# properties instead of "unknown version" in Explorer and in the MSI's ARP view.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={file_tuple},
    prodvers={file_tuple},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', '{publisher}'),
        StringStruct('FileDescription', '{description}'),
        StringStruct('FileVersion', '{file_version}'),
        StringStruct('InternalName', '{exe_base}'),
        StringStruct('LegalCopyright', '{copyright}'),
        StringStruct('OriginalFilename', '{exe_name}'),
        StringStruct('ProductName', '{product_name}'),
        StringStruct('ProductVersion', '{product_version}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def copyright_notice(year: int = 2026) -> str:
    return f"Copyright (c) {year} {PUBLISHER}. All rights reserved."


def version_info_text(version: str) -> str:
    parts = tuple(version_tuple(version)) + (0,) * (4 - len(version_tuple(version)))
    return VERSION_INFO_TEMPLATE.format(
        file_tuple=tuple(parts[:4]),
        publisher=PUBLISHER,
        description=f"{PRODUCT_NAME} - local-first job search autopilot",
        file_version=file_version(version),
        exe_base=EXE_BASENAME,
        copyright=copyright_notice(),
        exe_name=EXE_NAME,
        product_name=PRODUCT_NAME,
        product_version=msi_version(version),
    )


def wix_defines(version: str, arch: str = "x64") -> dict[str, str]:
    """``-d`` variables consumed by packaging/wix/JAUTOMATIC.wxs."""
    return {
        "ProductName": PRODUCT_NAME,
        "ProductSlug": PRODUCT_SLUG,
        "Publisher": PUBLISHER,
        "ExeName": EXE_NAME,
        "InstallFolder": INSTALL_FOLDER,
        "RegistryKey": REGISTRY_KEY,
        "ProductVersion": msi_version(version),
        "UpgradeCode": UPGRADE_CODE,
        "HelpLink": PROJECT_URL,
        "CopyrightNotice": copyright_notice(),
        "MinWindowsBuild": str(MIN_WINDOWS_BUILD),
        "Architecture": arch,
    }


def build_manifest(version: str, arch: str = "x64") -> dict:
    """Everything the build script / CI needs, as one JSON-serialisable dict."""
    return {
        "product_name": PRODUCT_NAME,
        "publisher": PUBLISHER,
        "exe_name": EXE_NAME,
        "install_folder": INSTALL_FOLDER,
        "version": version,
        "msi_version": msi_version(version),
        "file_version": file_version(version),
        "upgrade_code": UPGRADE_CODE,
        "architecture": arch,
        "release_name": release_name(version, arch),
        "wix": {"version": WIX_VERSION, "extensions": WIX_EXTENSIONS},
        "wix_defines": wix_defines(version, arch),
        "url": PROJECT_URL,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Version/identity single source of truth")
    parser.add_argument("--json", action="store_true", help="print the build manifest as JSON")
    parser.add_argument("--version", action="store_true", help="print the package version")
    parser.add_argument("--msi-version", action="store_true", help="print the 3-part MSI version")
    parser.add_argument("--version-info", metavar="PATH",
                        help="write the PyInstaller version resource to PATH")
    parser.add_argument("--wix-defines", metavar="PATH",
                        help="write WiX -d defines as KEY=VALUE lines to PATH")
    parser.add_argument("--arch", default="x64")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    version = read_version()
    if args.version_info:
        Path(args.version_info).parent.mkdir(parents=True, exist_ok=True)
        Path(args.version_info).write_text(version_info_text(version), encoding="utf-8")
        print(f"wrote {args.version_info} ({file_version(version)})")
    if args.wix_defines:
        lines = [f"{key}={value}" for key, value in wix_defines(version, args.arch).items()]
        Path(args.wix_defines).write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {args.wix_defines}")
    if args.json:
        print(json.dumps(build_manifest(version, args.arch), indent=2))
    if args.version:
        print(version)
    if args.msi_version:
        print(msi_version(version))
    if not (args.json or args.version or args.msi_version or args.version_info
            or args.wix_defines):
        print(json.dumps(build_manifest(version, args.arch), indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
