"""Harvest a frozen app dir into WiX ``files.wxs`` (deterministic, no WiX needed).

A PyInstaller one-dir bundle is hundreds of files — Qt plugins, translations,
native DLLs — and the set shifts with every dependency upgrade, so the
installer does not hand-maintain that list.  Instead ``build.ps1`` runs this
module after freezing and compiles the generated ``files.wxs`` next to the
hand-written ``jautomatic.wxs`` shell::

    python packaging/gen_files_wxs.py dist\\jautomatic packaging\\files.wxs

Determinism guarantees (all covered by ``tests/test_packaging.py``):

* files and directories are emitted in sorted order;
* every ``Component`` carries a stable GUID derived from its bundle-relative
  path (``uuid5``), so rebuilds of an unchanged tree produce identical GUIDs
  and upgrades stay clean;
* every ``Id`` is a valid Windows Installer identifier (≤72 chars, leading
  letter/underscore) and unique within the file — collisions get a numeric
  suffix in first-seen order.

One file per component with the file as ``KeyPath``: the boring, repair-safe
layout every WiX guide recommends.
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import uuid
from pathlib import Path
from xml.sax.saxutils import escape


def _load_build_info():
    # NOTE: imported by file location, not as `packaging.build_info` — this
    # directory is deliberately NOT a package (no __init__.py), because a
    # top-level `packaging` package would shadow PyPI's `packaging` library
    # for every tool run from the repo root (including pip itself).
    here = Path(__file__).resolve().parent
    spec = importlib.util.spec_from_file_location(
        "jautomatic_build_info", here / "build_info.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


WIX_NAMESPACE = _load_build_info().WIX_NAMESPACE

# Fixed namespace seed: GUIDs must be stable forever, so this UUID is part of
# the installer's permanent identity — never change it.
GUID_NAMESPACE = uuid.UUID("e8f4c5d2-7b3a-4f1c-9e6d-5a8b0c2d4f7e")

_MSI_ID_MAX = 72
_UNSAFE_CHARS = re.compile(r"[^A-Za-z0-9_.]")


def sanitize_id(text: str) -> str:
    """Make ``text`` a valid Windows Installer identifier (≤72 chars)."""
    cleaned = _UNSAFE_CHARS.sub("_", text)
    if not cleaned or not (cleaned[0].isalpha() or cleaned[0] == "_"):
        cleaned = f"f_{cleaned}"
    return cleaned[:_MSI_ID_MAX]


def component_guid(relative_posix_path: str) -> str:
    """Stable component GUID for a bundle-relative path (forward slashes)."""
    return str(uuid.uuid5(GUID_NAMESPACE, f"jautomatic:msi:{relative_posix_path}")).upper()


class _IdAllocator:
    """Hands out unique sanitized Ids, first-seen order, deterministic."""

    def __init__(self) -> None:
        self._used: set[str] = set()

    def take(self, *candidates: str) -> str:
        for candidate in candidates:
            base = sanitize_id(candidate)
            text = base
            counter = 2
            while text in self._used:
                suffix = f"_{counter}"
                text = base[: _MSI_ID_MAX - len(suffix)] + suffix
                counter += 1
            if text not in self._used:
                self._used.add(text)
                return text
        raise AssertionError("unreachable")  # pragma: no cover


def _iter_files(frozen_dir: Path) -> list[Path]:
    return sorted(p for p in frozen_dir.rglob("*") if p.is_file())


def generate(frozen_dir: str | Path, frozen_var: str = "$(var.FrozenDir)") -> str:
    """Render ``files.wxs`` XML harvesting ``frozen_dir``.

    ``frozen_var`` is the WiX bind variable ``build.ps1`` passes with ``-d``
    pointing at the same directory; ``File/@Source`` is expressed through it
    so the generated file stays relocatable.
    """
    root = Path(frozen_dir)
    if not root.is_dir():
        raise FileNotFoundError(f"frozen app dir not found: {root}")
    files = _iter_files(root)
    if not files:
        raise ValueError(f"frozen app dir is empty: {root}")

    ids = _IdAllocator()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- GENERATED by packaging/gen_files_wxs.py — do not edit by hand. -->",
        f'<Wix xmlns="{WIX_NAMESPACE}">',
        "  <Fragment>",
        '    <DirectoryRef Id="INSTALLFOLDER">',
    ]
    component_refs: list[str] = []

    # Group files by parent dir so nested <Directory> elements open/close cleanly.
    by_dir: dict[str, list[Path]] = {}
    for path in files:
        by_dir.setdefault(path.parent.relative_to(root).as_posix(), []).append(path)

    dir_ids: dict[str, str] = {}

    def dir_id(rel: str) -> str:
        if rel not in dir_ids:
            dir_ids[rel] = ids.take(f"dir_{rel}")
        return dir_ids[rel]

    # Currently open <Directory> chain (each entry is one path segment).
    open_chain: list[str] = []

    def close_to(depth: int) -> None:
        while len(open_chain) > depth:
            open_chain.pop()
            lines.append(f"{'  ' * (len(open_chain) + 3)}</Directory>")

    for rel_dir in sorted(by_dir):
        parts = [] if rel_dir == "." else rel_dir.split("/")
        # Back up to the common prefix with the open chain, then descend.
        common = 0
        while (common < min(len(open_chain), len(parts))
               and open_chain[common] == parts[common]):
            common += 1
        close_to(common)
        while len(open_chain) < len(parts):
            segment = parts[len(open_chain)]
            prefix = "/".join(parts[: len(open_chain) + 1])
            lines.append(f"{'  ' * (len(open_chain) + 3)}"
                         f'<Directory Id="{dir_id(prefix)}" Name="{escape(segment)}">')
            open_chain.append(segment)
        for path in by_dir[rel_dir]:
            rel = path.relative_to(root)
            rel_posix = rel.as_posix()
            source = f"{frozen_var}\\{str(rel).replace('/', chr(92))}"
            stem = "MainExecutable" if rel_posix == "jautomatic.exe" else f"file_{rel_posix}"
            # NOTE: no hash()-based fallbacks anywhere here — hash() is salted
            # per process, so any Id derived from it would break determinism.
            # _IdAllocator.take() already de-duplicates with numeric suffixes.
            file_id = ids.take(stem)
            comp_id = ids.take(f"comp_{file_id}")
            guid = component_guid(rel_posix)
            indent = "  " * (len(open_chain) + 3)
            lines.append(f'{indent}<Component Id="{comp_id}" Guid="{guid}" Bitness="always64">')
            lines.append(f'{indent}  <File Id="{file_id}" Source="{escape(source)}" KeyPath="yes" />')
            lines.append(f"{indent}</Component>")
            component_refs.append(comp_id)
    close_to(0)

    lines.append("    </DirectoryRef>")
    lines.append('    <ComponentGroup Id="FrozenFiles">')
    for ref in component_refs:
        lines.append(f'      <ComponentRef Id="{ref}" />')
    lines.append("    </ComponentGroup>")
    lines.append("  </Fragment>")
    lines.append("</Wix>")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gen_files_wxs.py", description=__doc__)
    parser.add_argument("frozen_dir", help="PyInstaller output dir (dist/jautomatic)")
    parser.add_argument("output", help="where to write files.wxs")
    args = parser.parse_args(argv)
    try:
        text = generate(args.frozen_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f"gen_files_wxs: {exc}", file=sys.stderr)
        return 1
    Path(args.output).write_text(text, encoding="utf-8")
    files = text.count("<File ")
    print(f"harvested {files} files -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
